#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Term::ANSIColor;

use Palette;
use Tile;

my $palette = Palette->new;


my $tile_1 = Tile->new( $palette );

print Dumper $tile_1;

$tile_1->set( $palette, "color" => "blue" );

print Dumper $tile_1;

my $tile_2 = Tile->new( $palette, "color" => "red" );

print Dumper $tile_2;

$tile_2->color( $palette, "green" );

print Dumper $tile_2;

print Dumper $tile_1->printf( $palette, 1 ), "\n";
print Dumper $tile_1->printf( $palette, 2 ), "\n";
print Dumper $tile_1->printf( $palette, 3 ), "\n";
print Dumper $tile_2->printf( $palette, 1 ), "\n";
print Dumper $tile_2->printf( $palette, 2 ), "\n";
print Dumper $tile_2->printf( $palette, 3 ), "\n";

my $random_tile_1 = Tile->new( $palette, "color" => "random" );
print Dumper $random_tile_1;

my $random_tile_2 = Tile->new( $palette );
$random_tile_2->color( $palette, "random" );
print Dumper $random_tile_2;

print Dumper $random_tile_2->match_color;

my $random_tile_3 = Tile->new( $palette, "color" => "critical" );
print Dumper $random_tile_3->match_color;

